services:
  topz:
    image: iaindavisdotdev/topz-multiarch
    container_name: sidecar-topz-02-topz
    platform: linux/arm64
    command: [
      "/server",
      "--addr=0.0.0.0:8080"
    ]
    networks:
      - sidecar-topz-02-network
    ports:
      - "8090:8080"
    pid: "container:sidecar-topz-02-nginx"
    privileged: true
  nginx:
    image: nginx
    container_name: sidecar-topz-02-nginx
    networks:
      - sidecar-topz-02-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  sidecar-topz-02-network:
    driver: bridge
    name: sidecar-topz-02-network
