apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  type: NodePort
  selector:
    app: whoami-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 32000
  sessionAffinity: None